kind: pipeline
type: docker
name: validate

.node-image: &node-image
  image: node:14-alpine@sha256:5c33bc6f021453ae2e393e6e20650a4df0a4737b1882d389f17069dc1933fdc5

steps:
  - name: check node dependencies
    <<: *node-image
    commands:
      - npm audit --audit-level="high"
      - npm audit --production

  - name: install node dependencies
    <<: *node-image
    commands:
      - npm ci

  - name: javascript linter
    <<: *node-image
    commands:
      - npm run linter
    depends_on:
      - install node dependencies

  - name: docker linter
    image: hadolint/hadolint:latest-alpine@sha256:e8ecdb235f7bbf2295148b72b86957cc041503c00e56d2e6928693f20710cd27
    commands:
      - hadolint Dockerfile

  - name: unit tests
    <<: *node-image
    commands:
      - npm test
    depends_on:
      - install node dependencies

---
kind: pipeline
type: docker
name: build
depends_on:
  - validate

steps:
  - name: generate tags
    image: alpine
    commands:
      - echo -n "$DRONE_COMMIT" > .tags

  - name: docker build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD
      repo: alsmith/find-denizens
    depends_on:
      - generate tags

  - name: scan image
    image: aquasec/trivy
    commands:
      - trivy "alsmith/find-denizens:$DRONE_COMMIT"
    depends_on:
      - docker build
